"""phase7_class_session_attendance

Revision ID: 1b0527789234
Revises: 756224cfe85c
Create Date: 2026-08-10 21:40:41.067835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b0527789234'
down_revision: Union[str, Sequence[str], None] = '756224cfe85c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class_sessions', sa.Column('teacher_id', sa.Integer(), nullable=False))
    op.add_column('class_sessions', sa.Column('department_id', sa.Integer(), nullable=False))
    op.add_column('class_sessions', sa.Column('semester', sa.Integer(), nullable=False))
    op.add_column('class_sessions', sa.Column('section', sa.String(length=10), nullable=False))
    op.add_column('class_sessions', sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('class_sessions', 'timetable_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_class_sessions_department_id'), 'class_sessions', ['department_id'], unique=False)
    op.create_index(op.f('ix_class_sessions_section'), 'class_sessions', ['section'], unique=False)
    op.create_index(op.f('ix_class_sessions_semester'), 'class_sessions', ['semester'], unique=False)
    op.create_index(op.f('ix_class_sessions_teacher_id'), 'class_sessions', ['teacher_id'], unique=False)
    op.create_foreign_key(None, 'class_sessions', 'departments', ['department_id'], ['id'])
    op.create_foreign_key(None, 'class_sessions', 'users', ['teacher_id'], ['id'])
    op.drop_column('class_sessions', 'ended_at')
    op.drop_column('class_sessions', 'attendance_submitted_at')
    op.drop_column('class_sessions', 'attendance_locked_at')
    
    # Migrate SessionStatus enum: scheduled/live/submitted/locked -> active/submitted
    # Create new enum type first
    op.execute("CREATE TYPE sessionstatus_new AS ENUM ('active', 'submitted')")
    # Convert existing rows (table is empty, but be safe): cast via text
    op.execute("ALTER TABLE class_sessions ALTER COLUMN status DROP DEFAULT")
    op.execute("""
        ALTER TABLE class_sessions 
        ALTER COLUMN status TYPE sessionstatus_new 
        USING (
            CASE status::text 
                WHEN 'scheduled' THEN 'active' 
                WHEN 'live' THEN 'active' 
                WHEN 'locked' THEN 'submitted' 
                ELSE status::text 
            END
        )::sessionstatus_new
    """)
    op.execute("DROP TYPE sessionstatus")
    op.execute("ALTER TYPE sessionstatus_new RENAME TO sessionstatus")
    op.execute("ALTER TABLE class_sessions ALTER COLUMN status SET DEFAULT 'active'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class_sessions', sa.Column('attendance_locked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('class_sessions', sa.Column('attendance_submitted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('class_sessions', sa.Column('ended_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'class_sessions', type_='foreignkey')
    op.drop_constraint(None, 'class_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_class_sessions_teacher_id'), table_name='class_sessions')
    op.drop_index(op.f('ix_class_sessions_semester'), table_name='class_sessions')
    op.drop_index(op.f('ix_class_sessions_section'), table_name='class_sessions')
    op.drop_index(op.f('ix_class_sessions_department_id'), table_name='class_sessions')
    op.alter_column('class_sessions', 'timetable_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('class_sessions', 'submitted_at')
    op.drop_column('class_sessions', 'section')
    op.drop_column('class_sessions', 'semester')
    op.drop_column('class_sessions', 'department_id')
    op.drop_column('class_sessions', 'teacher_id')
    # ### end Alembic commands ###
