"""Add student name

Revision ID: 756224cfe85c
Revises: a373351e9d67
Create Date: 2026-08-10 19:31:09.467463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '756224cfe85c'
down_revision: Union[str, Sequence[str], None] = 'a373351e9d67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profiles', sa.Column('name', sa.String(length=255), nullable=True))
    op.execute("UPDATE student_profiles SET name = 'Unknown Student'")
    op.alter_column('student_profiles', 'name', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_profiles', 'name')
    # ### end Alembic commands ###
