"""Configure safe user deletion cascades

Revision ID: dc6ba12d3d3c
Revises: e4c609fe1ae9
Create Date: 2026-08-31 11:44:39.322041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc6ba12d3d3c'
down_revision: Union[str, Sequence[str], None] = 'e4c609fe1ae9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('attendance_disputes_resolved_by_fkey'), 'attendance_disputes', type_='foreignkey')
    op.create_foreign_key(None, 'attendance_disputes', 'users', ['resolved_by'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('attendance_records_marked_by_fkey'), 'attendance_records', type_='foreignkey')
    op.create_foreign_key(None, 'attendance_records', 'users', ['marked_by'], ['id'], ondelete='SET NULL')
    op.alter_column('audit_logs', 'actor_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('audit_logs_actor_user_id_fkey'), 'audit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'audit_logs', 'users', ['actor_user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('class_sessions', 'teacher_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('class_sessions_teacher_id_fkey'), 'class_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'class_sessions', 'users', ['teacher_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('notifications_recipient_user_id_fkey'), 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'users', ['recipient_user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('password_reset_tokens_user_id_fkey'), 'password_reset_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'password_reset_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('student_profiles_user_id_fkey'), 'student_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'student_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('student_transfers', 'transferred_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('student_transfers_transferred_by_fkey'), 'student_transfers', type_='foreignkey')
    op.create_foreign_key(None, 'student_transfers', 'users', ['transferred_by'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('teacher_profiles_user_id_fkey'), 'teacher_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'teacher_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teacher_profiles', type_='foreignkey')
    op.create_foreign_key(op.f('teacher_profiles_user_id_fkey'), 'teacher_profiles', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'student_transfers', type_='foreignkey')
    op.create_foreign_key(op.f('student_transfers_transferred_by_fkey'), 'student_transfers', 'users', ['transferred_by'], ['id'])
    op.alter_column('student_transfers', 'transferred_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'student_profiles', type_='foreignkey')
    op.create_foreign_key(op.f('student_profiles_user_id_fkey'), 'student_profiles', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'password_reset_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('password_reset_tokens_user_id_fkey'), 'password_reset_tokens', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key(op.f('notifications_recipient_user_id_fkey'), 'notifications', 'users', ['recipient_user_id'], ['id'])
    op.drop_constraint(None, 'class_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('class_sessions_teacher_id_fkey'), 'class_sessions', 'users', ['teacher_id'], ['id'])
    op.alter_column('class_sessions', 'teacher_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.create_foreign_key(op.f('audit_logs_actor_user_id_fkey'), 'audit_logs', 'users', ['actor_user_id'], ['id'])
    op.alter_column('audit_logs', 'actor_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'attendance_records', type_='foreignkey')
    op.create_foreign_key(op.f('attendance_records_marked_by_fkey'), 'attendance_records', 'users', ['marked_by'], ['id'])
    op.drop_constraint(None, 'attendance_disputes', type_='foreignkey')
    op.create_foreign_key(op.f('attendance_disputes_resolved_by_fkey'), 'attendance_disputes', 'users', ['resolved_by'], ['id'])
    # ### end Alembic commands ###
